version: '3.8'
services:
  api: 
    build: .
    container_name: cooljob-api
    ports:
      - 8585:8585 
    volumes:
      - redis_data:/data
  redis-db:
    container_name: redis-db
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS="--requirepass ${REDIS_PASS} --save 60 1000 --appendonly yes"
    ports:
      - 6379:6379
      # Redis Insight Port
      - 13332:8001


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=cool-job-cluster
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch2
    environment:
      - node.name=es02
      - cluster.name=cool-job-cluster
      - cluster.initial_master_nodes=es01,es02
      #- discovery.type=single-node
      - discovery.seed_hosts=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9201:9201

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=khoram_soltan
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  redis_data:
    driver: local
