version: '3.8'
services:
  app:
    image: digikala_crawler
    build: .
    # environment:
    #   - PLAYWRIGHT_BROWSERS_PATH=/app/.cache/ms-playwright  # Optional: Sets a fixed location for Playwright browsers

volumes:
  data:  # This named volume corresponds to the one used in the service definition
